export const HISTORY_FIELD_LABELS: Record<string, string> = {
  progress: "진행 상태",
  order_type: "주문 유형",
  krw: "원화매입",
  price_rub: "판매가(루블)",
  prepayment_rub: "선결제(루블)",
  quantity: "수량",
  product_name: "상품명",
  product_type: "카테고리",
  product_option: "옵션",
  brand: "브랜드",
  unit_price_usd: "단가(USD)",
  recipient_name: "수취인 이름",
  recipient_phone: "수취인 전화",
  recipient_email: "수취인 이메일",
  zip_code: "우편번호",
  region: "지역",
  city: "도시",
  address: "주소",
  customs_number: "통관번호",
  gift: "선물 여부",
  photo_sent: "사진 발송",
};
